name: test

on:
    pull_request:
        branches:
          - main
        paths-ignore:
          - '.github/workflows/publish.yml'
          - '.github/FUNDING.yml'
          - '**README.md'
          - '.gitignore'
          - 'LICENSE'
jobs:
    tests-package:
        strategy:
          matrix:
            os: [ubuntu-latest, macOS-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Rust tooling
              uses: dtolnay/rust-toolchain@stable
            - name: Cache rust
              uses: Swatinem/rust-cache@v2
            - name: Test Rust
              run: cargo test
